### PR TITLE
Fixed and improved

### PR DESCRIPTION
**Pull request by sharedprophet**
I saw you abandoned this project, but I really wanted to use it, so I got it working properly. If you don't want to manage the repo anymore, could you make me the owner of the package on atom.io so I can push out this update?

### CODE REVIEW

**Comment by xcezzz** [comment]
Will update you now.

**Comment by xcezzz** [comment]
I honestly have no idea how to switch owners for packages on atom.io

I at least published an update to atom.io so it will reflect for updates.

**Comment by sharedprophet** [comment]
Thanks. You do whatever you like with the atom.io package; the doc for how to add a contributor or change ownership is at http://flight-manual.atom.io/behind-atom/sections/maintaining-your-packages/

**Comment by xcezzz** [comment]
Ahh I see. So apparently you being setup now as a collaborator through GitHub should allow you publish access on atom.io

**Comment by sharedprophet** [comment]
Excellent. Thanks.

**Pull request merged**
